# Generated by Django 5.1.5 on 2025-02-03 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zutat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('menge', models.CharField(max_length=100)),
                ('einheit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rezept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('beschreibung', models.TextField(max_length=1000)),
                ('zubereitungszeit', models.DateTimeField()),
                ('zutaten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zutaten', to='ApiRezeptverwaltung.zutat')),
            ],
        ),
    ]
