# Generated by Django 5.1.5 on 2025-02-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRezeptverwaltung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezept',
            name='zubereitungszeit',
            field=models.PositiveIntegerField(),
        ),
        migrations.RemoveField(
            model_name='rezept',
            name='zutaten',
        ),
        migrations.AddField(
            model_name='rezept',
            name='zutaten',
            field=models.ManyToManyField(related_name='zutaten', to='ApiRezeptverwaltung.zutat'),
        ),
    ]
